version: "3"

services:

  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:z
      - ./logs/postgres:/usr/src/app/logs
    env_file: .env

  graphql-pingator:
    restart: always
    container_name: graphql-pingator
    build:
      context: .
      dockerfile: ./src/Dockerfile
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - ./src:/usr/src/app/src
    env_file: .env
