const SCENE_NAME_ENDPOINTS = 'endpoints'
const SCENE_NAME_ADD_ENDPOINT = 'add-endpoint'
const SCENE_NAME_DELETE_ENDPOINT = 'delete-endpoint'

module.exports = { SCENE_NAME_ENDPOINTS, SCENE_NAME_ADD_ENDPOINT, SCENE_NAME_DELETE_ENDPOINT }