import { config } from 'dotenv';
config()

let {
	CONSOLE_LOGGING_LEVELS = `custom,info,error,warn,query`,
	TELEGRAM_BOT_API_TOKEN,
	POSTGRES_DB, POSTGRES_HOST, POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_PORT
} = process.env

CONSOLE_LOGGING_LEVELS = CONSOLE_LOGGING_LEVELS.split(`,`);

export {
	CONSOLE_LOGGING_LEVELS,
	TELEGRAM_BOT_API_TOKEN,
	POSTGRES_DB, POSTGRES_HOST, POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_PORT
};