require('dotenv').config();

export let {
	CONSOLE_LOGGING_LEVELS = `custom,info,error,warn,query`,
	DEV_TELEGRAM_BOT_API_TOKEN,
	POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, POSTGRES_HOST, POSTGRES_PORT
} = process.env;

CONSOLE_LOGGING_LEVELS = CONSOLE_LOGGING_LEVELS.split(`,`);

export default {
	CONSOLE_LOGGING_LEVELS,
	DEV_TELEGRAM_BOT_API_TOKEN,
	POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, POSTGRES_HOST, POSTGRES_PORT
};
// module.exports = {
// 	CONSOLE_LOGGING_LEVELS,
// 	DEV_TELEGRAM_BOT_API_TOKEN,
// 	POSTGRES_USER, POSTGRES_PASSWORD, POSTGRES_DB, POSTGRES_HOST, POSTGRES_PORT
// };