import { config } from 'dotenv';
config()

let {
	CONSOLE_LOGGING_LEVELS = `custom,info,error,warn,query`,
	TELEGRAM_BOT_API_TOKEN,
	POSTGRES_DB, POSTGRES_HOST, POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_PORT,
	PG_BOSS_POSTGRES_DB,
	PG_BOSS_POSTGRES_HOST,
	PG_BOSS_POSTGRES_PASSWORD,
	PG_BOSS_POSTGRES_PORT,
	PG_BOSS_POSTGRES_USER,
	PG_BOSS_RETRY_BACKOFF = 'false',
	PG_BOSS_SCHEMA = 'pgboss'
} = process.env

CONSOLE_LOGGING_LEVELS = CONSOLE_LOGGING_LEVELS.split(`,`);

export {
	CONSOLE_LOGGING_LEVELS,
	TELEGRAM_BOT_API_TOKEN,
	POSTGRES_DB, POSTGRES_HOST, POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_PORT,
	PG_BOSS_POSTGRES_DB,
	PG_BOSS_POSTGRES_HOST,
	PG_BOSS_POSTGRES_PASSWORD,
	PG_BOSS_POSTGRES_PORT,
	PG_BOSS_POSTGRES_USER,
	PG_BOSS_RETRY_BACKOFF,
	PG_BOSS_SCHEMA
};