import { config } from 'dotenv';

config();

let {
	CONSOLE_LOGGING_LEVELS = `custom,info,error,warn,query`,
	TELEGRAM_BOT_API_TOKEN,
	POSTGRES_DB, POSTGRES_HOST, POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_PORT,
	PG_BOSS_POSTGRES_DB,
	PG_BOSS_POSTGRES_HOST,
	PG_BOSS_POSTGRES_PASSWORD,
	PG_BOSS_POSTGRES_PORT,
	PG_BOSS_POSTGRES_USER,
	PG_BOSS_RETRY_BACKOFF = 'false',
	PG_BOSS_SCHEMA = 'pgboss',
	PG_BOSS_JOB_CHECK_INTERVAL_MS = '200',
	ENDPOINTS_PER_PAGE = '5'
} = process.env;

CONSOLE_LOGGING_LEVELS = CONSOLE_LOGGING_LEVELS.split(`,`);
PG_BOSS_JOB_CHECK_INTERVAL_MS = Number(PG_BOSS_JOB_CHECK_INTERVAL_MS);
ENDPOINTS_PER_PAGE = Number.parseInt(ENDPOINTS_PER_PAGE);

export {
	CONSOLE_LOGGING_LEVELS,
	TELEGRAM_BOT_API_TOKEN,
	POSTGRES_DB, POSTGRES_HOST, POSTGRES_PASSWORD, POSTGRES_USER, POSTGRES_PORT,
	PG_BOSS_POSTGRES_DB,
	PG_BOSS_POSTGRES_HOST,
	PG_BOSS_POSTGRES_PASSWORD,
	PG_BOSS_POSTGRES_PORT,
	PG_BOSS_POSTGRES_USER,
	PG_BOSS_RETRY_BACKOFF,
	PG_BOSS_SCHEMA,
	PG_BOSS_JOB_CHECK_INTERVAL_MS,
	ENDPOINTS_PER_PAGE
};